#!/bin/bash

# Exit build script on first failure
set -e

# Echo commands to stdout.
set -x

# Location of app source files.
SOURCE_DIR=app

# Location of unit tests.
TEST_DIR=tests

# Delete pyc files from previous builds.
find . -name "*.pyc" -delete

# Run unit tests.
python -m unittest discover

# Check that source has correct formatting.
yapf \
  --diff \
  --recursive \
  --style google \
  ./ \
  --exclude=third_party/* \
  --exclude=venv/*

# Run static analysis for Python bugs/cruft.
pyflakes "${SOURCE_DIR}/" "${TEST_DIR}/"
