#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

python3 -m venv ./venv
. venv/bin/activate
pip install --requirement requirements.txt
./e2e/test-csv-to-yaml
VIDEOS_DIR=/processed-videos
./e2e/test-render-scenes "$VIDEOS_DIR"
./e2e/test-publish-to-mediagoblin "$VIDEOS_DIR"