#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

VIDEOS_DIR="$1"
MEDIAGOBLIN_CONTAINER_NAME="$2"
MEDIAGOBLIN_VIDEOS_DIR="$3"

python3 -m venv ./venv
. venv/bin/activate
pip install --requirement requirements.txt
./e2e/test-csv-to-yaml
./e2e/test-render-scenes "$VIDEOS_DIR"
./e2e/test-publish-to-mediagoblin "$MEDIAGOBLIN_CONTAINER_NAME" "$MEDIAGOBLIN_VIDEOS_DIR"