#!/bin/bash

# Exit build script on first failure
set -e

# Echo commands to stdout.
set -x

wget https://github.com/mtlynch/free-usage-videos/blob/master/texas-farm-family-1952/TexasFar1952.mp4?raw=true

# TODO: Finish test.