#!/bin/bash

# Exit build script on first failure
set -e

# Echo commands to stdout.
set -x

RAW_VIDEOS_DIR=$(mktemp -d)
pushd "$RAW_VIDEOS_DIR"
wget https://github.com/mtlynch/free-usage-videos/blob/master/texas-farm-family-1952/TexasFar1952.mp4?raw=true \
  -O TexasFar1952.mp4
popd

if [ -n "$1" ]; then
  PROCESSED_VIDEOS_DIR="$1"
else
  PROCESSED_VIDEOS_DIR=$(mktemp -d)
fi

app/render_scenes.py \
  --metadata e2e/testdata/golden/scene-metadata.yaml \
  --raw_videos_dir "$RAW_VIDEOS_DIR" \
  --output_clips_dir "$PROCESSED_VIDEOS_DIR"

ACTUAL_LS_OUTPUT=$(mktemp)
ls "$PROCESSED_VIDEOS_DIR" \
   --sort=time \
   --reverse \
   --quoting-style=literal \
  -1 \
  > "$ACTUAL_LS_OUTPUT"

GOLDEN_LS_OUTPUT="e2e/testdata/golden/processed-clips-output.txt"
diff --context=2 "$GOLDEN_LS_OUTPUT" "$ACTUAL_LS_OUTPUT"